### ISSUE TITLE
C# Language Server Keep Crashing

### ISSUE THREAD

**Issue by robbytarigan** [dotnet/vscode-csharp#5964]
Type: <b>Bug</b>

## Issue Description ##
C# Language server keep crashing, so intellisense and go to definition cannot work anymore. 

## Steps to Reproduce ##
Install C# Dev Kit on Windows with WSL. Open a project in WSL

## Expected Behavior ##
Intellisense and go to definition can work.

## Actual Behavior ##
Intellisense and go to definition does not work.

### C# log ###
<details>
Dotnet path: /usr/bin/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
[Error - 2:05:22 PM] Server initialization failed.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 2:05:22 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 2:05:22 PM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 2:05:22 PM] The Microsoft.CodeAnalysis.LanguageServer server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

</details>

### C# LSP Trace Logs ###
<details>
Extension vscode.configuration-editing does not contribute csharpExtensionLoadPaths
Extension vscode.css-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.debug-auto-launch does not contribute csharpExtensionLoadPaths
Extension vscode.debug-server-ready does not contribute csharpExtensionLoadPaths
Extension vscode.emmet does not contribute csharpExtensionLoadPaths
Extension vscode.extension-editing does not contribute csharpExtensionLoadPaths
Extension vscode.git does not contribute csharpExtensionLoadPaths
Extension vscode.git-base does not contribute csharpExtensionLoadPaths
Extension vscode.github does not contribute csharpExtensionLoadPaths
Extension vscode.grunt does not contribute csharpExtensionLoadPaths
Extension vscode.gulp does not contribute csharpExtensionLoadPaths
Extension vscode.html-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.ipynb does not contribute csharpExtensionLoadPaths
Extension vscode.jake does not contribute csharpExtensionLoadPaths
Extension vscode.json-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.markdown-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.markdown-math does not contribute csharpExtensionLoadPaths
Extension vscode.merge-conflict does not contribute csharpExtensionLoadPaths
Extension ms-vscode.js-debug does not contribute csharpExtensionLoadPaths
Extension ms-vscode.vscode-js-profile-table does not contribute csharpExtensionLoadPaths
Extension vscode.npm does not contribute csharpExtensionLoadPaths
Extension vscode.php-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.references-view does not contribute csharpExtensionLoadPaths
Extension vscode.search-result does not contribute csharpExtensionLoadPaths
Extension vscode.typescript-language-features does not contribute csharpExtensionLoadPaths
Extension amazonwebservices.aws-toolkit-vscode does not contribute csharpExtensionLoadPaths
Extension eamodio.gitlens does not contribute csharpExtensionLoadPaths
Extension formulahendry.dotnet-test-explorer does not contribute csharpExtensionLoadPaths
Extension jebbs.plantuml does not contribute csharpExtensionLoadPaths
Extension ms-azuretools.vscode-docker does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.csdevkit does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.csharp does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.dotnet-interactive-vscode does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.vscode-dotnet-runtime does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.vscodeintellicode-csharp does not contribute csharpExtensionLoadPaths
Extension ms-kubernetes-tools.vscode-kubernetes-tools does not contribute csharpExtensionLoadPaths
Extension ms-python.isort does not contribute csharpExtensionLoadPaths
Extension ms-python.python does not contribute csharpExtensionLoadPaths
Extension ms-python.vscode-pylance does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.jupyter does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.jupyter-renderers does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.vscode-jupyter-cell-tags does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.vscode-jupyter-slideshow does not contribute csharpExtensionLoadPaths
Extension ms-vscode.live-server does not contribute csharpExtensionLoadPaths
Extension ms-vscode.powershell does not contribute csharpExtensionLoadPaths
Extension redhat.vscode-yaml does not contribute csharpExtensionLoadPaths
Extension ryanluker.vscode-coverage-gutters does not contribute csharpExtensionLoadPaths
Extension urbanoanderson.vscode-coverlet does not contribute csharpExtensionLoadPaths
Extension VisualStudioExptTeam.intellicode-api-usage-examples does not contribute csharpExtensionLoadPaths
Extension VisualStudioExptTeam.vscodeintellicode does not contribute csharpExtensionLoadPaths
</details>

## Environment information ##

**VSCode version**: 1.80.1
**C# Extension**: 2.0.312
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.306/

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  6.0.412 [/usr/share/dotnet/sdk]
  7.0.302 [/usr/share/dotnet/sdk]
  7.0.306 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.16 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.7.22362.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|aws-toolkit-vscode|amazonwebservices|1.81.0|amazonwebservices.aws-toolkit-vscode-1.81.0|
|csdevkit|ms-dotnettools|0.2.100|ms-dotnettools.csdevkit-0.2.100-linux-x64|
|csharp|ms-dotnettools|2.0.312|ms-dotnettools.csharp-2.0.312-linux-x64|
|dotnet-interactive-vscode|ms-dotnettools|1.0.4313020|ms-dotnettools.dotnet-interactive-vscode-1.0.4313020|
|dotnet-test-explorer|formulahendry|0.7.8|formulahendry.dotnet-test-explorer-0.7.8|
|gitlens|eamodio|14.1.1|eamodio.gitlens-14.1.1|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.7|visualstudioexptteam.intellicode-api-usage-examples-0.2.7|
|isort|ms-python|2023.10.1|ms-python.isort-2023.10.1|
|jupyter|ms-toolsai|2023.6.1101941928|ms-toolsai.jupyter-2023.6.1101941928-linux-x64|
|jupyter-renderers|ms-toolsai|1.0.17|ms-toolsai.jupyter-renderers-1.0.17|
|live-server|ms-vscode|0.4.9|ms-vscode.live-server-0.4.9|
|plantuml|jebbs|2.17.5|jebbs.plantuml-2.17.5|
|powershell|ms-vscode|2023.6.0|ms-vscode.powershell-2023.6.0|
|python|ms-python|2023.12.0|ms-python.python-2023.12.0|
|vscode-coverage-gutters|ryanluker|2.11.0|ryanluker.vscode-coverage-gutters-2.11.0|
|vscode-coverlet|urbanoanderson|1.1.5|urbanoanderson.vscode-coverlet-1.1.5|
|vscode-docker|ms-azuretools|1.26.0|ms-azuretools.vscode-docker-1.26.0|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.8|ms-toolsai.vscode-jupyter-cell-tags-0.1.8|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|ms-toolsai.vscode-jupyter-slideshow-0.1.5|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.3.13|ms-kubernetes-tools.vscode-kubernetes-tools-1.3.13|
|vscode-pylance|ms-python|2023.7.40|ms-python.vscode-pylance-2023.7.40|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|visualstudioexptteam.vscodeintellicode-1.2.30|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-linux-x64|;

</details>

Extension version: 2.0.312
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by dibarbet** [comment]
Interesting - while I dig more into this, would you be able to update the `dotnet.server.trace` setting to `Trace` and attach the C# output window logs again?  That might have some more clues on what is going wrong.

One area where I've seen similarish errors is if the device is running out of disk space - though unlikely is your wsl drive running out of space?

**Comment by robbytarigan** [comment]
Thank you for your reply. It looks I cannot replicate the issue after a turning my machine off on Friday and turning it on back again today (Monday).  I'll update the issue once I can see it again.

It's interesting you mention about disk space, so it perhaps more related with WSL issue than C# Dev Kit extension itself.

**Comment by omarmciver** [comment]
@dibarbet Even with `dotnet.server.trace` I still get only this output:
![image](https://github.com/dotnet/vscode-csharp/assets/56705059/045567e2-97cc-45d7-9990-32039a161140)

Does this provide any kind of indicator where I should go looking next?

**Comment by omarmciver** [comment]
I removed the follow devcontainer defined extensions, and allowed the csdevkit to handle all the dependencies, and the issue seems to have gone away.

![image](https://github.com/microsoft/vscode-dotnettools/assets/56705059/ef71499e-4f29-40b9-8ba4-563a2a3d445b)

**Comment by rhuanbarros** [comment]
in my case, the source of the problems was Gitlens extension.

**Comment by fnfup** [comment]
> in my case, the source of the problems was Gitlens extension.

as in I have to disable gitlens?

**Comment by mcxufly** [comment]
> in my case, the source of the problems was Gitlens extension.

same problem, when I uninstall the gitlens the language server is working as normal

**Comment by mcxufly** [comment]
> > in my case, the source of the problems was Gitlens extension.
> 
> same problem, when I uninstall the gitlens the language server is working as normal
No, the problem is not solved, the language server is still crashing.

**Comment by dibarbet** [comment]
We just published 2.45.25 to the marketplace.  Assuming this has the same cause as https://github.com/dotnet/vscode-csharp/issues/7514 this should fix the issue.

Please let me know if it does not.

**Comment by mcxufly** [comment]
> We just published 2.45.25 to the marketplace. Assuming this has the same cause as #7514 this should fix the issue.
> 
> Please let me know if it does not.

the problem seems solved now

**Comment by sodiqyekeen** [comment]
I still experience this issue on my Mac. So, I have to restart vs code every now and then.

**Comment by mcxufly** [comment]
The problem still exists, I'm writing a rather large C# project in VSCode on linux and the code highlighting is all wrong and doesn't show the documentation, but the references and such are correct.

**Comment by dibarbet** [comment]
Going to close this issue - it's a year old and it's becoming a bit of a catch all for various likely unrelated problems. 

@mcxufly (and anyone else having problems) can you please file a new issue with the following details
1.  A screenshot of the incorrect highlighting, and which theme you're using.
1.  Set `dotnet.server.trace` to `Trace`, reload the window, and attach the 'C#' output window logs when you hit the issue.
2.  Make sure the file shows the correct project in the active file context: 
    ![image](https://github.com/user-attachments/assets/2dc0c710-1359-4f77-b621-36afd9b9a8bc)
4.  If using C# Dev Kit, make sure the file shows in the solution explorer
