### ISSUE TITLE
Stuck at Starting Server

### ISSUE THREAD

**Issue by eisber** [dotnet/vscode-csharp#6049]
Type: <b>Bug</b>

Running via VSCode remote/SSH on ubuntu

Dotnet path: /home/marcozo/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.9/dotnet
Activating C# standalone...
info: LanguageServerHost[0]
      Starting server...

Extension version: 2.0.328
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.0-1041-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2155 CPU @ 3.30GHz (20 x 3312)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.68GB (88.59GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bmarcozo-synapseml/home/marcozo/SynapseML-Enya --crash-reporter-id 9b6895ef-5391-4b21-8358-35c76b8617f4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: marcozo-synapseml|
|OS|Linux x64 5.15.0-1041-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (16 x 3111)|
|Memory (System)|62.74GB (57.69GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by rho-cassiopeiae** [comment]
Same thing on versions 2.0.328 and .320.
1.26.0 version works fine.

**Comment by seansimonanimation** [comment]
Damn. @rho-cassiopeiae beat me to it. Yes, it's an issue with the latest couple versions. Simply downgrade to an older version in the extension manager and it'll work fine.

**Comment by TrieBr** [comment]
I think the extension still works* even when it gets stuck on that log. I think it just doesn't log anything after it's started.

In my case most of the functions work* even when it's stuck on this log (references, higlighting, autocomplete).

*About 50% of the time.

**Comment by arkalyanms** [comment]
That log is spurious and was fixed last week. Please let us know if there is a feature that is broken.

**Comment by rho-cassiopeiae** [comment]
The extension absolutely doesn't work and it's not a problem with logs, or at least the logs are not the main problem.

**Comment by procopym** [comment]
Language Server still not starting...
I am using same setup as initially described in issue.
Also had to downgrade to 1.26.0.

Why issue was closed?

**Comment by glenn2223** [comment]
I got mine to work by installing the [C# Dev Kit](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit). It still says `Starting server...` and nothing else, but the IntelliCode, and what not, is now working as before.

Though the C# extension says: _[`... for C# and is shipped along with C# Dev Kit`](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp#:~:text=shipped%20along%20with%20C%23%20Dev%20Kit)_, it definitely shouldn't completely rely on it and not work without it IMO 😁

**Comment by procopym** [comment]
Unfortunately, didn't work for me

**Comment by KonstantinLukaschenko** [comment]
Had to downgrade to `1.26.0` as well.

**Comment by mkfrey** [comment]
For me switching to Pre-Release version worked as well.
